# serverless.yml

component: scf # (必填) 引用 component 的名称，当前用到的是 tencent-scf 组件
name: nodejs-qrcode # (必填) 该组件创建的实例名称
org:  # (可选) 用于记录组织信息，默认值为您的腾讯云账户 appid
app: nodejs-qrcode-app # (可选) 该 SCF 应用名称
stage: dev # (可选) 用于区分环境信息，默认值是 dev

inputs:
  name: nodejs-qrcode
  src: ./src
  runtime: Nodejs10.15 # 云函数的运行时环境。除 Nodejs10.15 外，可选值为：Python2.7、Python3.6、Nodejs6.10、Nodejs8.9、PHP5、PHP7、Golang1、Java8。
  region: ap-guangzhou
  handler: index.qrcode
  exclude:
      - .gitignore
      - .git/**
  events:
    - apigw:
        name: nodejs_qrcode_apigw
        parameters:
          protocols:
            - http
            - https
          serviceName: nodejs-qrcode
          description: The service of Serverless Framework
          environment: release
          endpoints:
            - path: /
              method: ANY
              function:
                  isIntegratedResponse: true